import { MasterListEntityKey } from '../settings/data/masterEntities';

export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  ForgotPassword: undefined;
  OtpVerification: undefined;
  ResetPassword: undefined;
  Dashboard: undefined;
  Notifications: undefined;
  MyProfile: undefined;
  ChangePassword: undefined;
  ModulePlaceholder: { title: string };
  ProductList: undefined;
  AddProduct: { mode?: 'add' | 'edit'; productId?: string } | undefined;
  ProductDetails: { productId: string };
  CustomerList: undefined;
  CustomerDetails: { customerId: string };
  OrderList: undefined;
  OrderDetails: { orderId: string };
  EmiApplicationList: undefined;
  EmiApplicationDetails: { applicationId: string };
  FiCaseList: undefined;
  FiCaseDetails: { fiCaseId: string };
  CreditReviewDetails: { applicationId: string };
  DownPaymentDetails: { applicationId: string };
  ESignDetails: { applicationId: string };
  EkycDetails: { applicationId: string };
  MandateDetails: { applicationId: string };
  DisbursementDetails: { applicationId: string };
  EmiOrderDetails: { applicationId: string };
  DispatchDetails: { applicationId: string };
  ReportsHome: undefined;
  UserList: undefined;
  UserDetails: { userId: string };
  AddUser: { mode?: 'add' | 'edit'; userId?: string } | undefined;
  SettingsHome: undefined;
  MastersHome: undefined;
  MasterList: { entity: MasterListEntityKey };
  CategoriesMaster: undefined;
  BranchMaster: undefined;
  PincodeMaster: undefined;
};
