import { EmiPaymentStatus } from '@prisma/client';
import { NotificationPriority, NotificationType } from '../repository/notification.repository';
import { jsonDb } from '../../../config/json-db';
import { notificationRepository } from '../repository/notification.repository';
import { notificationService } from './notification.service';
import { loanRepository } from '../../loan/repository/loan.repository';

/**
 * Asia/Kolkata offset in minutes (IST). Schedule `dueDate`s are generated by
 * buildEmiSchedule from the loan start instant (e.g. 2026-09-07T18:30:00.000Z
 * == midnight IST), so the reminder windows MUST be computed in IST regardless
 * of the server's local timezone — Vercel functions run in UTC and would
 * otherwise skip the "due tomorrow" pass entirely.
 */
const IST_OFFSET_MIN = 5 * 60 + 30;

function startOfDay(date: Date): Date {
  // Shift to IST wall-clock, truncate to midnight, shift back to the UTC
  // instant of IST midnight. Timezone-agnostic — identical on dev and prod.
  const istWall = new Date(date.getTime() + IST_OFFSET_MIN * 60_000);
  istWall.setUTCHours(0, 0, 0, 0);
  return new Date(istWall.getTime() - IST_OFFSET_MIN * 60_000);
}

function addDays(date: Date, days: number): Date {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d;
}

/**
 * Reminder engine — scans EMI schedule for due-tomorrow and overdue instalments.
 *
 * Data model (json-db, mirrors Supabase):
 *  - Loans live in the `loanAccount` collection (NOT `loan_accounts`).
 *  - Schedule rows live in `emi_schedules`, keyed to the loan via
 *    `loanAccountId`, with the status persisted in `paymentStatus`
 *    (NOT `status`) and the due date in `dueDate` (NOT `due_date`).
 *
 * Execution:
 *  - Dev / long-running server: started via `startNotificationReminderEngine()`
 *    from server.ts (interval + immediate first pass).
 *  - Production (Vercel serverless): `setInterval` cannot survive a cold start,
 *    so the pass is also exposed as GET {API_PREFIX}/internal/reminders and
 *    driven by a Vercel Cron entry (see vercel.json + app.ts).
 */
export async function runEmiReminderPass(asOf: Date = new Date()): Promise<{
  dueTomorrow: number;
  overdue: number;
}> {
  const today = startOfDay(asOf);
  const tomorrow = addDays(today, 1);
  const dayAfter = addDays(today, 2);

  const allSchedules = jsonDb.findMany('emi_schedules', {});
  const rowsWithLoans = allSchedules
    .map((s: any) => {
      const loanAccount = jsonDb.findOne('loanAccount', { id: s.loanAccountId });
      return { ...s, loanAccount };
    })
    .filter((s: any) => s.loanAccount && s.loanAccount.loanStatus === 'ACTIVE');

  // Persist OVERDUE for past-due PENDING rows so the schedule (and any admin
  // view reading `paymentStatus`) stays accurate — markOverdue is otherwise
  // never called anywhere.
  const overdueLoanIds = new Set<string>();
  for (const s of rowsWithLoans) {
    if (
      s.paymentStatus === EmiPaymentStatus.PENDING &&
      s.dueDate &&
      new Date(s.dueDate).getTime() < today.getTime()
    ) {
      overdueLoanIds.add(s.loanAccountId);
    }
  }
  for (const loanId of overdueLoanIds) {
    await loanRepository.markOverdue(loanId, today);
  }

  const activeSchedules = rowsWithLoans.filter((s: any) =>
    s.paymentStatus === EmiPaymentStatus.PENDING ||
    s.paymentStatus === EmiPaymentStatus.OVERDUE,
  );

  const dueTomorrowRows = activeSchedules.filter((s: any) => {
    if (!s.dueDate) return false;
    const dueDate = new Date(s.dueDate).getTime();
    return dueDate >= tomorrow.getTime() && dueDate < dayAfter.getTime();
  });

  const overdueRows = activeSchedules.filter((s: any) => {
    if (!s.dueDate) return false;
    const dueDate = new Date(s.dueDate).getTime();
    return dueDate < today.getTime();
  });

  let dueTomorrow = 0;
  let overdue = 0;

  for (const row of dueTomorrowRows) {
    const reminderKey = `EMI_DUE:${row.id}:${tomorrow.toISOString().slice(0, 10)}`;
    const existing = await notificationRepository.findReminderDuplicate(
      row.loanAccount.userId,
      reminderKey,
    );
    if (existing) continue;

    await notificationService.dispatch({
      userId: row.loanAccount.userId,
      type: NotificationType.EMI_DUE_REMINDER,
      title: 'EMI due tomorrow',
      message: `EMI #${row.emiNumber} of ₹${Number(row.emiAmount).toFixed(2)} is due tomorrow.`,
      priority: NotificationPriority.MEDIUM,
      metadata: {
        reminderKey,
        emiId: row.id,
        emiNumber: row.emiNumber,
        loanAccountNumber: row.loanAccount.loanAccountNumber,
      },
      channels: ['inapp', 'email', 'sms', 'whatsapp'],
    });
    dueTomorrow += 1;
  }

  for (const row of overdueRows) {
    const reminderKey = `EMI_OVERDUE:${row.id}:${today.toISOString().slice(0, 10)}`;
    const existing = await notificationRepository.findReminderDuplicate(
      row.loanAccount.userId,
      reminderKey,
    );
    if (existing) continue;

    await notificationService.dispatch({
      userId: row.loanAccount.userId,
      type: NotificationType.EMI_OVERDUE,
      title: 'EMI overdue',
      message: `EMI #${row.emiNumber} is overdue. Please pay to avoid late fees.`,
      priority: NotificationPriority.HIGH,
      metadata: {
        reminderKey,
        emiId: row.id,
        emiNumber: row.emiNumber,
        loanAccountNumber: row.loanAccount.loanAccountNumber,
      },
      channels: ['inapp', 'email', 'sms', 'whatsapp'],
    });
    overdue += 1;
  }

  return { dueTomorrow, overdue };
}

let timer: ReturnType<typeof setInterval> | null = null;

export function startNotificationReminderEngine(intervalMs = 60 * 60 * 1000): void {
  if (timer) return;

  const tick = () => {
    void runEmiReminderPass()
      .then((result) => {
        if (result.dueTomorrow || result.overdue) {
          console.info(
            `[Reminders] dueTomorrow=${result.dueTomorrow} overdue=${result.overdue}`,
          );
        }
      })
      .catch((error) => console.error('[Reminders] pass failed', error));
  };

  tick();
  timer = setInterval(tick, intervalMs);
}

export function stopNotificationReminderEngine(): void {
  if (timer) {
    clearInterval(timer);
    timer = null;
  }
}
